### ISSUE TITLE
[feat] 채팅 페이지 컴포넌트 개발

### ISSUE THREAD

**Issue by justkeepgoin** [weather-eottae-dev/frontend#3]
## Description
웹소켓을 이용한 실시간 채팅 기능 UI 구현

## To-do
- [ ] 채팅 메세지 버블창, 메세지 보내기 UI 화면 
- [ ] 상단 공지사항 이미지 슬라이드
- [ ] 지역 서버 버튼
